### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wavefront** [dehesa/CodableCSV#12]
I have a large csv file (> 400,000 lines) which is too big to decode in one blob, so I loop through each line of the file by calling readLine(), and then for each line:

convert the line to Data
let obj = try decoder.decode([Obj].self, from: data).first

It seems that if you call decoder.decode repeatedly that it leaks memory. It looks like the allocation of Buffer() from the initialiser of CSVReader has a retain cycle.
I haven't yet had time to dive into this - am wiling to do so if no other advice. See attached memory graph.
<img width="999" alt="Screen Shot 2020-03-11 at 8 19 29 pm" src="https://user-images.githubusercontent.com/3782641/76449989-b9866d00-63d5-11ea-9729-52f1792413e6.png">

**Comment by wavefront** [comment]
Sorry, looks like this was reported and fixed only a day ago. Closing and I'll verify

**Comment by wavefront** [comment]
Sorry, looks like this was reported and fixed only a day ago. Closing and I'll verify

**Comment by dehesa** [comment]
Hi @wavefront,

Thank you for reporting. The problem was indeed filed and it has been fixed (under the best of my knowledge). I will strongly suggest you to upgrade to version 0.4.1 (or later, depending on when you read this).

The decoder implementation has been reworked to use small-size value types and not depend on protocols (as previously) which should improve performance and, at the same time, get away with any reference cycle.

**Comment by dehesa** [comment]
> I have a large csv file (> 400,000 lines) which is too big to decode in one blob, so I loop through each line of the file by calling `readLine()`, and then for each line: `try decoder.decode([Obj].self, from: data).first`.

Oh, that is annoying. There is actually an easy solution for that: adding a `decode(_ type:from:encoding:)` function to `CSVDecoder` that accepts a file handle instead of a data blob (as it is now). The function would transform the file handle into an `OutputStream` and only request lines on-demand. That way it wouldn't have to load the whole file in memory.

I had the task already in my TODO list. If you really want it and you are ready to be my beta tester 😅, I can build it fairly quickly.

**Comment by wavefront** [comment]
Sure thing. Happy to help. Its not super urgent for me since I need to keep the readline() approach [To fix up badly formatted csv before submitting to DecodableCSV]. Let me know when something ready to test.
