### ISSUE TITLE
Handling CSV file with empty line after header

### ISSUE THREAD

**Issue by noahemmet** [dehesa/CodableCSV#18]
Hi! I'm looking for the correct configuration to handle a CSV file that has an empty line after the header, like so:
```
"Item Code","ItemStatus"

"ABC","In Stock"
"DEF","Unavailable"
```
The callsite looks like this:
```
let decoder = CSVDecoder { config in
  config.headerStrategy = .firstLine
}
let items = try decoder.decode([Item].self, from: csvString)
// items == []
```

I've used various combinations of `delimiters.row = "\n"`, `escapingStrategy = "\n"`, and `trimStrategry = .whitespaces`, but the decoder either throws an error or returns an empty array. Is there a way to ignore empty lines?

## System (please complete the following information)
 - OS: macOS 10.15.4
 - CodableCSV: 0.5.1

**Comment by dehesa** [comment]
Hi @noahemmet,

There are currently no configuration values for non-standard header rows, such as your case or multi-line headers. However, I have been able to decode your sample file _as intended_ performing the following steps:
1. Update to the latest CodableCSV.
   Version 0.5.4 introduces _lazy_ decoding, which we will use to solve your problem. To update to the latest version modify the SPM `Package.swift` file (if necessary).
   ```swift
   dependencies: [
       .package(url: "https://github.com/dehesa/CodableCSV.git", from: "0.5.4")
   ],
   ```
   Tell Xcode to update the library: `File > Swift Packages > Update to latest package version`.
2. Define a Codable representation for your sample file.
   ```swift
   let input = #"""
   "Item Code","ItemStatus"
   
   "ABC","In Stock"
   "DEF","Unavailable"
   """#

   struct Item: Decodable {
       let code: String
       let status: String
       
       private enum CodingKeys: String, CodingKey {
           case code = "Item Code"
           case status = "ItemStatus"
       }
   }
   ```
3. Decode the sample _lazily_ and skip the first row after the header.
   ```swift
   let decoder = CSVDecoder { $0.headerStrategy = .firstLine }
   var lazySequence = try decoder.lazy(from: input)
   let _ = sequence.next()
   while let row = sequence.next() {
       let item = try row.decode(Item.self)
       print(item)
   }
   ```
4. Bonus point: Since you are decoding sequentially you can reduce memory usage by setting the `.sequential` buffering strategy on the decoder initialization.
   ```swift
   let decoder = CSVDecoder {
       $0.headerStrategy = .firstLine
       $0.bufferingStrategy = .sequential
   }
   ```

Regards,
Marcos

**Comment by noahemmet** [comment]
Ah thank you for your detailed reply, the lazy sequencing did it!
