### ISSUE TITLE
Cocoapods installation is not possible

### ISSUE THREAD

**Issue by xsleonard** [dehesa/CodableCSV#23]
## Describe the bug

The pod name "CodableCSV" is occupied by a different project with the same name as this one: https://github.com/pauljohanneskraft/CodableCSV.

Following the pod install instructions for this repo will fail.

The error message from pod is:

```
[!] CocoaPods could not find compatible versions for pod "CodableCSV":
  In Podfile:
    CodableCSV (~> 0.6.1)

None of your spec sources contain a spec satisfying the dependency: `CodableCSV (~> 0.6.1)`.
```

Performing a `pod search CodableCSV`:

```
-> CodableCSV (0.4.0)
   CodableCSV allows you to encode and decode CSV files using Codable model types.
   pod 'CodableCSV', '~> 0.4.0'
   - Homepage: https://github.com/pauljohanneskraft/CodableCSV
   - Source:   https://github.com/pauljohanneskraft/CodableCSV.git
   - Versions: 0.4.0, 0.2.0, 0.1.1 [trunk repo]
```

## To Reproduce

Add `pod "CodableCSV", "~> 0.6.1"` to Podfile, as per the readme.
Perform:
`pod install`

## Expected behavior

This package will be installed by pod.

**Comment by dehesa** [comment]
Hi @xsleonard 

The Cocoapods support was added by a contributor sometime ago. I am not a Cocoapods user and I can't test the correct behavior since I don't have any Cocoapods projects. I will be happy the perform the required changes to make it work, but I need some detailed indications.

**Comment by lienbacher** [comment]
I just tried installing via pods and faced the same issue, this link might help, but i honestly have very little clue: https://guides.cocoapods.org/making/specs-and-specs-repo.html#how-do-i-update-an-existing-pod
currently running SwiftCSV, and it takes hours to parse a 40mb csv file, hoping your project will do better.

**Comment by dehesa** [comment]
Hi @lienbacher 

I was hoping someone who uses Cocoapods would jump up and help out, but it seems I will have to get to know Cocoapods. I will try to fix the problems this week.

Addressing your performance remarks: I haven't compared Codable CSV against any other CSV library out there yet, but I am using it daily with files that weight between 200 & 500 MB and I measure in seconds (sometimes minutes). So I hope CodableCSV will do better. I have a long list of TODOs with performance improvements in CodableCSV. Till now I was focusing on correct behavior, but the next step in [the roadmap](https://github.com/dehesa/CodableCSV#roadmap) is performance (I am quite inspired by [Daniel Lemire's parser](https://www.youtube.com/watch?v=wlvKAT7SZIQ)).

Please notice that using ObjC classes (or Swift objects backed by ObjC objects) on repeating code, such as a CSV parser, may account for 90% or more of your runtime. This is due to the low performance characteristics of ObjC message passing and the retain and release calls. I thoroughly recommend profiling your code with Instruments (or similar tools). As a rule of thumb, try to not call anything that smell like ObjC (e.g. `DateFormatter`s) if you have more than 1k rows in your CSV.

**Comment by kimball** [comment]
For anyone who may be unaware, until the collision can be resolved you can use this in your `Podfile`

`pod 'CodableCSV', :git => 'https://github.com/dehesa/CodableCSV.git', :commit => '<#commit SHA#>'`

where `<#commit SHA#>` is the git SHA of the release you want to use. You will just need to update it manually if you want to use a new release.

**Comment by dehesa** [comment]
I managed to tracked down the owner of the pod colliding with `CodableCSV` and he was nice enough to transfer me ownership. Props for his readiness!

I push the 0.6.5 version to Cocoapods trunk. Now it should work without problems. Please keep in mind that this is the first version in Cocoapods; therefore, you can now ask Cocoapods for versions with lower numbers.

Please, let me know if there is any further problems.
