### ISSUE TITLE
Question: What's more efficient about supplying init(from:)?

### ISSUE THREAD

**Issue by emma-k-alexandra** [dehesa/CodableCSV#8]
From the README:

> The previous example will work if the CSV file has a header row and the header titles match exactly the property names (name, age, and hasPet). **A more efficient and detailed implementation**:
> ```swift
> struct Student: Decodable {
>    let name: String
>    let age: Int
>    let hasPet: Bool
>
>    init(from decoder: Decoder) throws {
>        var row = try decoder.unkeyedContainer()
>        self.name = try row.decode(String.self)
>        self.age = try row.decode(Int.self)
>        self.hasPet = try row.decode(Boolean.self)
>    }
>}
>```

What makes this implementation more efficient than the implementation listed above it?

> ```swift
> struct School: Decodable {
>    // The custom CSV file is a list of all the students.
>    let people: [Student]
>}
>
>struct Student: Decodable {
>    let name: String
>    let age: Int
>    let hasPet: Bool
>}
>```

Are there benchmarks to show the implementation with `init(from:)` is more efficient? Should I implement all of my `Codable` structures with a manual `init(from:)`?

**Comment by dehesa** [comment]
Hi @emma-k-alexandra,

Using [`unkeyedContainer()`](https://github.com/dehesa/CodableCSV/blob/master/Sources/Codable/Decodable/ShadowDecoder.swift#L49) instead of [keyed containers](https://github.com/dehesa/CodableCSV/blob/master/Sources/Codable/Decodable/ShadowDecoder.swift#L61) has two main benefits (relating to performance):
- Fields are iterated in the order they are decoded and therefore there are no jumps within the underlying array of `String`s.
- There is no need for `CodingKey`s when using `unkeyedContainer`s, which eliminates the whole [conversion from `CodingKey` to `String` to `Int`](https://github.com/dehesa/CodableCSV/blob/master/Sources/Codable/Decodable/Containers/Record/DecodingRecordRandom.swift#L92).

Personally, I don't optimize code till it is necessary, since readability (and fewer lines of code) makes my programming life easier.

Regarding your question of benchmark, I don't have any 😅 Although, it shouldn't be very hard to generate a file with more than 3k random rows and test it out with `CFAbsoluteTimeGetCurrent()` or the `XCTest` functionality. I will write it down in my todo, but if you want to challenge yourself, maybe you could send a PR 🙃
